### ISSUE TITLE
可否调整字体大小……？

### ISSUE THREAD

**Issue by lolisound** [Tsuk1ko/bilibili-live-chat#3]
在obs的浏览器css中设置font-size并不管用……以及如果支持本地字体就更好了0.0

**Comment by Tsuk1ko** [comment]
不`!important`的情况下你需要对特定的 class 设置 font-size，而不是直接对 body

你可以参照原有 [css](https://github.com/Tsuk1ko/bilibili-live-chat/blob/master/docs/main.css)，推荐用 [Stylus](https://add0n.com/stylus.html) 扩展在浏览器中进行样式调试

**Comment by lolisound** [comment]
了解，谢谢！
如果可以的话了，直接在 bilivechat.moe.best 中设置字体会方便的多。

**Comment by Tsuk1ko** [comment]
其实设置字体大小这个需求应该很少会有

1. 你可以在 OBS 中通过修改浏览器来源长宽，并配合变换来达到任意的实际大小
2. 如果你修改了 css，那么字体和其他元素（例如头像）的比例就会被改变，如果这不是你想要的结果你可能还得顺带把这些元素的大小也调整一遍

**Comment by WordlessEcho** [comment]
缩放会糊，我自己摸的一套：

```css
.danmaku-author-name, .danmaku-message {
  font-size: 2.3em;
  line-height: normal;
}

.danmaku-author-face {
  width: 48px;
  height: 48px;
  border-radius: 48px;
}
```

OBS内浏览器宽高为625*1080
